markdown: kramdown
title: Li Song
name: Li Song
timezone: Asia/Shanghai
permalink: /:categories/:title
cdn_path: https://s3.eu-west-2.amazonaws.com/notimportant/archive/
assets:
  css_compressor: sass
